spring:
  application:
    name: socialnetwork

  security:
    enabled: true   # 🔥 Seguridad activada explícitamente
    jwt:
      secret: "rpoeVRlEjaXO0YvU7sn1mfhZ7RJm8GtjYvWA1vbz+bQ="
      expiration: 3600000

  datasource:
    url: jdbc:postgresql://localhost:5433/backend_social_network
    username: admin
    password: admin

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    health:
      probes:
        enabled: true

  metrics:
    tags:
      application: socialnetwork


